### ISSUE TITLE
Import Error - No module named ScheduleAndDepend.Clusterer

### ISSUE THREAD

**Issue by nev1n** [siavooshpayandehazad/SoCDep2#1]
Description :  On running the Main.py module, the following import module error is received.

  "File "Main.py", line 6, in <module>
   from ScheduleAndDepend.Clusterer import Clustering, Clustering_Functions
   ImportError: No module named ScheduleAndDepend.Clusterer "

Notes:
Found for Commit Version -> 60dcf930d5
Python Version -> Python 2.7.6

**Comment by siavooshpayandehazad** [comment]
It doesn't give me such error. please remove all the python generated files and re-index.

**Comment by siavooshpayandehazad** [comment]
The issue was about the addressing the files in import command (IDE related)... now resolved...

**Comment by nev1n** [comment]
Issue appears to be fixed for Build commit 'd8d57bd1a22eecd5793ddaa99d64b5e9288c1cde'.
Status changed from resolved -> Closed
