### ISSUE TITLE
Pictures for Wiki

### ISSUE THREAD

**Issue by siavooshpayandehazad** [siavooshpayandehazad/SoCDep2#2]
![different_state_transisions](https://cloud.githubusercontent.com/assets/6337603/12847018/015c7dee-cc19-11e5-895d-716e576015eb.png)

![counter_threshold_viz](https://cloud.githubusercontent.com/assets/6337603/12610156/d512baa4-c4ee-11e5-9d4d-afba7540fb77.png)

![rg3D](https://cloud.githubusercontent.com/assets/6337603/9054119/592755aa-3a86-11e5-81bc-8424eca206f1.png)
![ag3D](https://cloud.githubusercontent.com/assets/6337603/9054048/b36ad61e-3a85-11e5-83d2-5ffb4301d375.png)
![system_diagram](https://cloud.githubusercontent.com/assets/6337603/8888311/3f38a1c6-32b1-11e5-8070-ecc212872d22.png)
 ![shm3D](https://cloud.githubusercontent.com/assets/6337603/9054074/f47612b8-3a85-11e5-9473-d98d2b05d161.png)
![mapping_opt_processSA](https://cloud.githubusercontent.com/assets/6337603/8672836/471a89a4-2a32-11e5-9cf2-6223ac2125ae.png)
![pmcg](https://cloud.githubusercontent.com/assets/6337603/8646519/3620a4aa-2959-11e5-9978-5089d6f8cfeb.png)
![shm](https://cloud.githubusercontent.com/assets/6337603/8667543/801e59e6-2a01-11e5-9053-7f21f5396b80.png)
![shm](https://cloud.githubusercontent.com/assets/6337603/8658475/3f80de34-29a4-11e5-8b86-33aa42d252b0.png)
![ttg](https://cloud.githubusercontent.com/assets/6337603/8646545/64ac404a-2959-11e5-9bdb-7160b5aba665.png)
![ag](https://cloud.githubusercontent.com/assets/6337603/8509395/3db68c18-22a9-11e5-88cc-aa623ea09b87.png)
![ctg_initial](https://cloud.githubusercontent.com/assets/6337603/8509397/3db9b4a6-22a9-11e5-8476-743996f04d28.png)
![ctg_opt_process](https://cloud.githubusercontent.com/assets/6337603/8509398/3db9dfda-22a9-11e5-97c4-285083a210f6.png)
![ctg_postopt](https://cloud.githubusercontent.com/assets/6337603/8509399/3dba3bb0-22a9-11e5-899e-1c18b3a4939f.png)
![mapping_num](https://cloud.githubusercontent.com/assets/6337603/8509400/3dbb2cc8-22a9-11e5-91b3-145f64dc4fd3.png)
![mapping_opt_process](https://cloud.githubusercontent.com/assets/6337603/8509396/3db8f5b6-22a9-11e5-9e04-ef894bec4403.png)
![mapping_util](https://cloud.githubusercontent.com/assets/6337603/8509401/3dd0fba2-22a9-11e5-9862-ad784b115799.png)
![mapping](https://cloud.githubusercontent.com/assets/6337603/8509425/a8bba3b2-22aa-11e5-8abe-f34232132ef2.png)
![rg](https://cloud.githubusercontent.com/assets/6337603/8509429/f1dcf69a-22aa-11e5-9300-a186499f3fa4.png)
![scheduling](https://cloud.githubusercontent.com/assets/6337603/8509403/3dd772b6-22a9-11e5-8d9d-56ac5a473dc9.png)
![tg](https://cloud.githubusercontent.com/assets/6337603/8509404/3dd81a04-22a9-11e5-9c67-9e1538f0eea4.png)
![animated](https://cloud.githubusercontent.com/assets/6337603/8552264/b34c9b06-24e4-11e5-830e-084cd946e382.gif)

**Comment by nev1n** [comment]
![1 original](https://cloud.githubusercontent.com/assets/9991252/12756862/4c0a7810-c9de-11e5-9a96-ddc609c1ed9d.png)

**Comment by nev1n** [comment]
![2 gen_shmu_arch](https://cloud.githubusercontent.com/assets/9991252/12756879/5f498056-c9de-11e5-8e3f-5026a6d8561c.png)
![2a all_wire_shmu_1](https://cloud.githubusercontent.com/assets/9991252/12756884/61beaa6e-c9de-11e5-8060-d8e72fdb1d91.png)
![2b mem_shmu](https://cloud.githubusercontent.com/assets/9991252/12756888/65d4235e-c9de-11e5-91f8-98945c76a4cd.png)

**Comment by nev1n** [comment]
![3 local_mem](https://cloud.githubusercontent.com/assets/9991252/12756891/6bde6e44-c9de-11e5-8fd8-257fb7c7fcc3.png)

**Comment by nev1n** [comment]
![fsm_design_1](https://cloud.githubusercontent.com/assets/9991252/13131745/5a147806-d5f6-11e5-8f2d-ba51a57d4791.png)
![fsm_design_2](https://cloud.githubusercontent.com/assets/9991252/13131751/5f184170-d5f6-11e5-82d3-59f289a6edca.png)
![fsm_design_3](https://cloud.githubusercontent.com/assets/9991252/13131761/64f532ec-d5f6-11e5-90f4-feae14a0f5dd.png)
![fsm_design_4](https://cloud.githubusercontent.com/assets/9991252/13131765/66d4b7d6-d5f6-11e5-8fb4-e6a8d35207f2.png)
![fsm_design_5](https://cloud.githubusercontent.com/assets/9991252/13131767/68d7c820-d5f6-11e5-84ea-27a1a79416b4.png)
![impl_fsm_design_1_3](https://cloud.githubusercontent.com/assets/9991252/13131774/75d73678-d5f6-11e5-88ac-58f9fa1f7ec7.png)
![impl_fsm_design_2](https://cloud.githubusercontent.com/assets/9991252/13131777/77819c52-d5f6-11e5-8c28-46e5e8bb02b2.png)
![impl_fsm_design_4_5](https://cloud.githubusercontent.com/assets/9991252/13131778/791629a2-d5f6-11e5-8ddf-75670ac1dbb0.png)

**Comment by siavooshpayandehazad** [comment]
![logo](https://cloud.githubusercontent.com/assets/6337603/14418625/cacaca68-ffc8-11e5-962d-f59383848a74.png)
